#!/bin/bash
if ! git add -A
then
	echo This is not a git directory
fi
if git status | grep -q "Changes to be committed"
then
	#commiting whithout or with the passed args
	if [[ $# == 0 ]]
	then
		git commit
	else
		git commit -m "$@"
	fi
	if [[ $? == 0 ]]
	then
		githook push
	fi
fi
