#!/bin/bash
git add -A
if ! git add -A
then
	echo this is not a git directory
fi

if git status | grep -q "Changes to be committed"
then
	if [[ $# == 0 ]]
	then
		git commit
	else
		git commit -m "$@"
	fi
	if [[ $? == 0 ]]
	then
		githook push
	fi
fi
